### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified 

### ISSUE THREAD

**Issue by spydan33** [huwprosser/carter-voice-assistant#10]
I'm getting this error when running app.py

`Hello there! I'm Jarvis, a personal AI assistant. How may I assist you today?
Traceback (most recent call last):
  File "C:\Users\dmerg\Documents\Projects\JARVIS\carter_project\app.py", line 170, in <module>
    jc = CarterClient(
         ^^^^^^^^^^^^^
  File "C:\Users\dmerg\Documents\Projects\JARVIS\carter_project\app.py", line 41, in __init__
    self.getOpener()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\dmerg\Documents\Projects\JARVIS\carter_project\app.py", line 154, in getOpener
    self.playAudio(output['audio'])
  File "C:\Users\dmerg\Documents\Projects\JARVIS\carter_project\app.py", line 101, in playAudio
    audio_data = AudioSegment.from_file(BytesIO(r.content)).export(format='wav')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmerg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dmerg\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1509, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
`
Not sure where to start debugging on this? any insights?

**Comment by ReluxGames** [comment]
i cant even start mine
