### ISSUE TITLE
'output' error

### ISSUE THREAD

**Issue by IberonXII** [huwprosser/carter-voice-assistant#12]
hi so i was working and trying to install this when i got this error. 

`Traceback (most recent call last):
  File "C:\Users\(name)\Downloads\carter-voice-assistant-main\carter-voice-assistant-main\app.py", line 170, in <module>
    jc = CarterClient(
         ^^^^^^^^^^^^^
  File "C:\Users\(name)\Downloads\carter-voice-assistant-main\carter-voice-assistant-main\app.py", line 41, in __init__
    self.getOpener()
    ^^^^^^^^^^^^^^^^
  File "C:\Users\(name)\Downloads\carter-voice-assistant-main\carter-voice-assistant-main\app.py", line 148, in getOpener
    output = agent_response['output']
             ~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'output'`

can anyone help me with this?

thx

**Comment by lfnicklangley** [comment]
@IberonXII  the API has clearly changed the params are now completely different. Hence why it can no longer parse output.

**Comment by LeVraiArdox** [comment]
You have to replace 'playerid' with 'user_id'. This should work
